name       : gnonlin
version    : 1.4.0
release    : 2
source     :
    - http://gstreamer.freedesktop.org/src/gnonlin/gnonlin-1.4.0.tar.xz : 2d667e1632816ea8a6ff7c8b75b29241b6542e1f6ab41d9d51661c287006667f
license    : LGPL-2.0
summary    : Library for creating non-linear video editors
description: |
    Library for creating non-linear video editors
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
